[package]
name="dataflow-reflect"
version = "0.1.0"
edition = "2021"

[dependencies]
const-default = "1.0.0"
const-default-derive = "*"
proc-macro2 = "1.0.46"
syn = {version = "1.0.102", features = ["extra-traits"]}

